
PROGRAM _INIT
	 
END_PROGRAM

PROGRAM _CYCLIC
//	//Master
//	MpAxisBasic_Primary.Power;
//	MpAxisBasic_Primary.Stop;
//	MpAxisBasic_Primary.MoveAbsolute;
//	MpAxisBasic_Primary.MoveAdditive;
//	MpAxisBasic_Primary.MoveVelocity;
//	MpAxisBasic_Primary.ErrorReset;
//	MpAxisBasic_Primary.Update;
//	MpAxisBasic_Primary.Enable;
//	MpAxisBasic_Primary.MpLink;
//	MpAxisBasic_Primary.Parameters;
//	
//	MpAxisBasicParameters_Primary.Velocity;
//	MpAxisBasicParameters_Primary.Distance;
//	MpAxisBasicParameters_Primary.Position;
//	MpAxisBasicParameters_Primary.Acceleration;
//	MpAxisBasicParameters_Primary.Deceleration;
//	MpAxisBasicParameters_Primary.Direction;
//	MpAxisBasicParameters_Primary.Stop.Deceleration;
//	
//	//Slave
//	MpAxisBasic_Primary.Velocity;
//	MpAxisBasic_Primary.Position;
//	MpAxisBasic_Primary.PowerOn;
//	MpAxisBasic_Primary.MoveActive;
//	MpAxisBasic_Primary.MoveDone;
//	MpAxisBasic_Primary.Error;
//	MpAxisBasic_Primary.UpdateDone;
//	MpAxisBasic_Primary.InVelocity;
//	MpAxisBasic_Primary.InPosition;
//	MpAxisBasic_Primary.Stopped;

END_PROGRAM

PROGRAM _EXIT
	 
END_PROGRAM

